<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mrules</string>
	</array>
	<key>name</key>
	<string>Maperitive Rules</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Simple line comments</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.mrules</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Quoted strings</string>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>comment.mrules</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Paths</string>
			<key>match</key>
			<string>\w+[/\.\w-]*/[/\.\w-]*\w</string>
			<key>name</key>
			<string>meta</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.mrules</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.mrules</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Zoom level maps like &lt;zoom&gt;:&lt;value&gt;</string>
			<key>match</key>
			<string>(\d+\.?\d*:)(-?\d+\.?\d*)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Colors and other numerics</string>
			<key>match</key>
			<string>#\h{3,6}|[-\+]?\d+\.?\d*%?</string>
			<key>name</key>
			<string>constant.numeric.mrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(features|rules|properties)\b</string>
			<key>name</key>
			<string>entity.name.tag.mrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(target|points|lines|areas)\b</string>
			<key>name</key>
			<string>entity.name.tag.mrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(define|draw)\b</string>
			<key>name</key>
			<string>entity.name.function.mrules</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>osm tags</string>
			<key>match</key>
			<string>\b\w+=</string>
			<key>name</key>
			<string>entity.name.function.mrules</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(stop|if|elseif|else|for|elsefor)\b</string>
			<key>name</key>
			<string>variable.parameter.mrules</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>spartial queries</string>
			<key>match</key>
			<string>(\[|\]|\(|\)|(area|node|way|relation|contour|gpstrack|gpsroute|gpswaypoint|gpspoint)\[|stop|NOT|AND|OR|[@\$]\w+|\*)</string>
			<key>name</key>
			<string>variable.parameter.mrules</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.mrules</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>everything else before the first :</string>
			<key>match</key>
			<string>(\w[ \.\w-]*\w)\s*:</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mrules</string>
	<key>uuid</key>
	<string>377ce4f3-ff59-41c7-9028-b69f954d28bd</string>
</dict>
</plist>
